version: '3.8'

services:
  video-merger-api:
    build: .
    container_name: video-merger-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=UTC
    volumes:
      - video-temp:/tmp/video_processing
      - video-output:/tmp/video_output
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 512M
    networks:
      - video-network

volumes:
  video-temp:
    driver: local
  video-output:
    driver: local

networks:
  video-network:
    driver: bridge
